<?php

/**
 * ClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaimTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Claim');
    }
}