<?php

/**
 * Claim
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kre
 * @subpackage model
 * @author     Garin Studio
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Claim extends BaseClaim
{
  public static
    $_types = array(
      1   =>  'Купить квартиру',
      2   =>  'Продать квартиру',
      3   =>  'Купить коммерческую недвижимость',
      4   =>  'Продать коммерческую недвижимость',
      5   =>  'Купить загородный дом, участок',
      6   =>  'Продать загородный дом, участок',
      7   =>  'Снять квартиру',
      8   =>  'Сдать квартиру',
      9   =>  'Снять коммерческую недвижимость',
      10  =>  'Сдать коммерческую недвижимость',
      11  =>  'Снять коттедж',
      12  =>  'Сдать коттедж',
    ),
    $_groups = array(
      1   => array('eliteflat', 'elitenew', 'penthouse'),
      2   => array('eliteflat', 'elitenew', 'penthouse'),
      3   => array('comsell'),
      4   => array('comsell'),
      5   => array('outoftown'),
      6   => array('outoftown'),
      7   => array('flatrent'),
      8   => array('flatrent'),
      9   => array('comrent'),
      10  => array('comrent'),
      11  => array('cottage'),
      12  => array('cottage')
    ),
    $_statuses = array(
      'new'       =>  'Новая',
      'resolved'  =>  'Обработана',
      'rejected'  =>  'Отклонена'
    );
  
  public function getHumanStatus()
  {
    return self::$_statuses[$this->status];
  }
}
