<?php

/**
 * Click
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kre
 * @subpackage model
 * @author     Garin Studio
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Click extends BaseClick
{
  public static function log($name, $day = null) {
    $click = Doctrine::getTable('Click')->createQuery()
        ->andWhere('day = ?', $day ? $day : date('Y-m-d'))
        ->andWhere('name = ?', $name)->execute(array());
    if(!count($click)){
      $click = new Click();
      $click->day  = $day ? $day : date('Y-m-d');
      $click->name = $name;
      $click->amount = 0;
    }
    else{
      $click = $click[0];
    }
    $click->amount++;
    $click->save();
  }
}
