<?php

/**
 * LotLogTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LotLogTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object LotLogTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('LotLog');
  }


  public function retrieveBackendLotLogList(Doctrine_Query $q)
  {
    return $q->leftJoin($q->getRootAlias().'.Lot l');
  }
}