<?php

/**
 * MainOfferTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MainOfferTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MainOfferTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('MainOffer');
  }

  public function clearLot($id)
  {
    return $this->createQuery()
            ->update()
            ->from('MainOffer')
            ->set('lot_id', 'NULL')
            ->set('lot_anons', 'NULL')
            ->set('lot_object', 'NULL')
            ->where('lot_id = ?', $id)
            ->execute();
  }
}