<?php

/**
 * Param
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kre
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Param extends BaseParam
{
  public static $_types = array(
    'base'    =>  'Основные',
    'about'   =>  'Описание объекта',
    'tech'    =>  'Технические параметры',
    'plot'    =>  'Земельный участок',
    'infra'   =>  'Инфраструктура',
    'flat'    =>  'Описание квартиры',
    'more'    =>  'Дополнительные параметры',
    'comm'    =>  'Коммуникации',
    'hidden'  =>  'Дополнительные параметры (для экспорта)'
  ),
    $_addressStructure = array(
    'region'       => 'регион',
    'district'     => 'район',
    'city'         => 'город',
    'street'       => 'улица',
    'house'        => 'дом',
    'building'     => 'корпус',
    'construction' => 'строение',
    'string'      => 'Адрес',
  ),
$_map = array(
  'comrent' => array (
    'base' => array (
      array (
        'field' => 'objecttype',
        'name' => 'Тип объекта',
        'property_id' => 1,
      ),
      array (
        'field' => 'estate',
        'name' => 'БЦ/ТРЦ',
        'property_id' => 2,
      ),
      array (
        'field' => 'distance_metro',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'payback',
        'name' => 'Окупаемость, лет',
        'property_id' => 84,
      ),
      array (
        'field' => 'yield',
        'name' => 'Доходность, %',
        'property_id' => 85,
      ),
      array (
        'field' => 'm_a_p',
        'name' => 'МАП',
        'property_id' => 86,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'm_a_p_Currency',
        'name' => 'Валюта',
        'property_id' => 87,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип здания',
        'property_id' => 4,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'goaluse',
        'name' => 'Варианты целевого использования',
        'property_id' => 5,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'buildclass',
        'name' => 'Класс помещения',
        'property_id' => 7,
        'use_for' => 'object',
      ),
      array (
        'field' => 'decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция здания',
        'property_id' => 11,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'constrfloors',
        'name' => 'Перекрытия этажей',
        'property_id' => 12,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'spaceuseful',
        'name' => 'Полезная площадь (м&sup2;)',
        'property_id' => 13,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'object',
      ),
      array (
        'field' => 'entergroup',
        'name' => 'Входная группа',
        'property_id' => 15,
        'use_for' => 'object',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция и кондиционирование',
        'property_id' => 16,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна и двери',
        'property_id' => 18,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_inner',
        'name' => 'Коммуникации',
        'property_id' => 19,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'electricity_power',
        'name' => 'Электрическая мощность, кВт',
        'property_id' => 20,
        'use_for' => 'object',
      ),
      array (
        'field' => 'fence',
        'name' => 'Огороженная территория',
        'property_id' => 21,
        'use_for' => 'supobject',
      ),
    ),
    'plot' => array (
      array (
        'field' => 'spaceplot',
        'name' => 'Площадь участка (сотки)',
        'property_id' => 22,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'plottype',
        'name' => 'Назначение земли',
        'property_id' => 23,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'plotlaw',
        'name' => 'Вид права',
        'property_id' => 24,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_services',
        'name' => 'Услуги',
        'property_id' => 28,
        'use_for' => 'supobject',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'comsell' => array (
    'base' => array (
      array (
        'field' => 'objecttype',
        'name' => 'Тип объекта',
        'property_id' => 1,
      ),
      array (
        'field' => 'estate',
        'name' => 'БЦ/ТРЦ',
        'property_id' => 2,
      ),
      array (
        'field' => 'distance_metro',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'payback',
        'name' => 'Окупаемость, лет',
        'property_id' => 84,
      ),
      array (
        'field' => 'yield',
        'name' => 'Доходность, %',
        'property_id' => 85,
      ),
      array (
        'field' => 'm_a_p',
        'name' => 'МАП',
        'property_id' => 86,
      ),
      array (
        'field' => 'm_a_p_Currency',
        'name' => 'Валюта',
        'property_id' => 87,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип здания',
        'property_id' => 4,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'goaluse',
        'name' => 'Варианты целевого использования',
        'property_id' => 5,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'buildclass',
        'name' => 'Класс помещения',
        'property_id' => 7,
        'use_for' => 'object',
      ),
      array (
        'field' => 'decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция здания',
        'property_id' => 11,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'constrfloors',
        'name' => 'Перекрытия этажей',
        'property_id' => 12,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'spaceuseful',
        'name' => 'Полезная площадь (м&sup2;)',
        'property_id' => 13,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'object',
      ),
      array (
        'field' => 'entergroup',
        'name' => 'Входная группа',
        'property_id' => 15,
        'use_for' => 'object',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция и кондиционирование',
        'property_id' => 16,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна и двери',
        'property_id' => 18,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_inner',
        'name' => 'Коммуникации',
        'property_id' => 19,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'electricity_power',
        'name' => 'Электрическая мощность, кВт',
        'property_id' => 20,
        'use_for' => 'object',
      ),
      array (
        'field' => 'fence',
        'name' => 'Огороженная территория',
        'property_id' => 21,
        'use_for' => 'supobject',
      ),
    ),
    'plot' => array (
      array (
        'field' => 'spaceplot',
        'name' => 'Площадь участка (сотки)',
        'property_id' => 22,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'plottype',
        'name' => 'Назначение земли',
        'property_id' => 23,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'plotlaw',
        'name' => 'Вид права',
        'property_id' => 24,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_services',
        'name' => 'Услуги',
        'property_id' => 28,
        'use_for' => 'supobject',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'cottage' => array (
    'base' => array (
      array (
        'field' => 'distance_mkad',
        'name' => 'Удаленность от МКАД',
        'property_id' => 31,
      ),
      array (
        'field' => 'spaceplot',
        'name' => 'Площадь участка (сотки)',
        'property_id' => 22,
      ),
      array (
        'field' => 'space',
        'name' => 'Площадь дома (кв.м)',
        'property_id' => 33,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'objecttype',
        'name' => 'Тип объекта',
        'property_id' => 1,
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'object',
      ),
      array (
        'field' => 'arch_style',
        'name' => 'Архитектурный стиль',
        'property_id' => 35,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'object',
      ),
      array (
        'field' => 'decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'object',
      ),
    ),
    'comm' => array (
      array (
        'field' => 'service_electricity',
        'name' => 'Электричество',
        'property_id' => 36,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_gas',
        'name' => 'Газоснабжение',
        'property_id' => 37,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_water',
        'name' => 'Водоснабжение',
        'property_id' => 38,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_drainage',
        'name' => 'Канализация',
        'property_id' => 39,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_inner',
        'name' => 'Внутридомовые коммуникации',
        'property_id' => 40,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_tele',
        'name' => 'Телекоммуникации',
        'property_id' => 41,
        'use_for' => 'object',
      ),
    ),
    'more' => array (
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_accomplishment',
        'name' => 'Инфраструктура и окружение',
        'property_id' => 42,
        'use_for' => 'supobject',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'only_plot',
        'name' => 'Только участок',
        'property_id' => 32,
      ),
      array (
        'field' => 'locality',
        'name' => 'Населенный пункт',
        'property_id' => 43,
      ),
      array (
        'field' => 'cottageVillage',
        'name' => 'Коттеджный посёлок',
        'property_id' => 44,
      ),
      array (
        'field' => 'type_of_land',
        'name' => 'Категория земель',
        'property_id' => 45,
      ),
      array (
        'field' => 'district_of',
        'name' => 'Район области',
        'property_id' => 46,
      ),
      array (
        'field' => 'export_to_cian',
        'name' => 'Экспорт в ЦИАН',
        'property_id' => 81,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
      array (
        'field' => 'settlements_tba',
        'name' => 'Коттеджные поселки для ТБА',
        'property_id' => 88,
      ),
    ),
  ),
  'eliteflat' => array (
    'base' => array (
      array (
        'field' => 'rooms',
        'name' => 'Количество комнат',
        'property_id' => 47,
        'use_for' => 'object',
      ),
      array (
        'field' => 'estate',
        'name' => 'Жилой комплекс',
        'property_id' => 2,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип дома',
        'property_id' => 48,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flats',
        'name' => 'Количество квартир',
        'property_id' => 49,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flatspaces',
        'name' => 'Площади квартир',
        'property_id' => 50,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'front',
        'name' => 'Фасад',
        'property_id' => 52,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'territory',
        'name' => 'Территория',
        'property_id' => 80,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'decorationtext',
        'name' => 'Отделка площадей общего пользования',
        'property_id' => 53,
        'use_for' => 'supobject',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция',
        'property_id' => 54,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 55,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'itp',
        'name' => 'Итп',
        'property_id' => 56,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна',
        'property_id' => 57,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'doors',
        'name' => 'Двери',
        'property_id' => 58,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'other',
        'name' => 'Прочее',
        'property_id' => 59,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_additional',
        'name' => 'Дополнительно',
        'property_id' => 60,
        'use_for' => 'supobject',
      ),
    ),
    'flat' => array (
      array (
        'field' => 'about_floorspace',
        'name' => 'Жилая площадь',
        'property_id' => 61,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_toilet',
        'name' => 'Количество санузлов',
        'property_id' => 62,
        'use_for' => 'object',
      ),
      array (
        'field' => 'market',
        'name' => 'Рынок',
        'property_id' => 79,
        'use_for' => 'object',
        'authorized_only' => 1,
      ),
      array (
        'field' => 'about_decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 77,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_balcony',
        'name' => 'Лоджии и балконы',
        'property_id' => 63,
        'use_for' => 'object',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'roomsfrom',
        'name' => 'Комнат от',
        'property_id' => 64,
      ),
      array (
        'field' => 'roomsto',
        'name' => 'Комнат до',
        'property_id' => 65,
      ),
      array (
        'field' => 'kitchen_area',
        'name' => 'Площадь кухни',
        'property_id' => 66,
      ),
      array (
        'field' => 'area_of_each_room',
        'name' => 'Площадь каждой комнаты',
        'property_id' => 67,
      ),
      array (
        'field' => 'about_count_bedrooms',
        'name' => 'Количество спален',
        'property_id' => 76,
      ),
      array (
        'field' => 'balconies',
        'name' => 'Кол-во балконов',
        'property_id' => 70,
      ),
      array (
        'field' => 'number_of_loggias',
        'name' => 'Кол-во лоджий',
        'property_id' => 71,
      ),
      array (
        'field' => 'passenger_elevators',
        'name' => 'Кол-во пасс. лифтов',
        'property_id' => 68,
      ),
      array (
        'field' => 'cargo_elevators',
        'name' => 'Кол-во груз. лифтов',
        'property_id' => 69,
      ),
      array (
        'field' => 'number_of_bathrooms_combined',
        'name' => 'Кол-во совм. с/у',
        'property_id' => 72,
      ),
      array (
        'field' => 'number_of_separate_toilets',
        'name' => 'Кол-во разд. с/у',
        'property_id' => 73,
      ),
      array (
        'field' => 'where_to_go_out_the_window',
        'name' => 'Куда выходят окна',
        'property_id' => 74,
      ),
      array (
        'field' => 'the_possibility_of_a_mortgage',
        'name' => 'Возможность ипотеки',
        'property_id' => 75,
      ),
      array (
        'field' => 'the_distance_from_the_metro_in_minutes',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'penthouse' => array (
    'base' => array (
      array (
        'field' => 'rooms',
        'name' => 'Количество комнат',
        'property_id' => 47,
        'use_for' => 'object',
      ),
      array (
        'field' => 'estate',
        'name' => 'Жилой комплекс',
        'property_id' => 2,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип дома',
        'property_id' => 48,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flats',
        'name' => 'Количество квартир',
        'property_id' => 49,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flatspaces',
        'name' => 'Площади квартир',
        'property_id' => 50,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'front',
        'name' => 'Фасад',
        'property_id' => 52,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'territory',
        'name' => 'Территория',
        'property_id' => 80,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'decorationtext',
        'name' => 'Отделка площадей общего пользования',
        'property_id' => 53,
        'use_for' => 'supobject',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция',
        'property_id' => 54,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 55,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'itp',
        'name' => 'Итп',
        'property_id' => 56,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна',
        'property_id' => 57,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'doors',
        'name' => 'Двери',
        'property_id' => 58,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'other',
        'name' => 'Прочее',
        'property_id' => 59,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_additional',
        'name' => 'Дополнительно',
        'property_id' => 60,
        'use_for' => 'supobject',
      ),
    ),
    'flat' => array (
      array (
        'field' => 'about_floorspace',
        'name' => 'Жилая площадь',
        'property_id' => 61,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_toilet',
        'name' => 'Количество санузлов',
        'property_id' => 62,
        'use_for' => 'object',
      ),
      array (
        'field' => 'market',
        'name' => 'Рынок',
        'property_id' => 79,
        'use_for' => 'object',
        'authorized_only' => 1,
      ),
      array (
        'field' => 'about_decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 77,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_balcony',
        'name' => 'Лоджии и балконы',
        'property_id' => 63,
        'use_for' => 'object',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'roomsfrom',
        'name' => 'Комнат от',
        'property_id' => 64,
      ),
      array (
        'field' => 'roomsto',
        'name' => 'Комнат до',
        'property_id' => 65,
      ),
      array (
        'field' => 'kitchen_area',
        'name' => 'Площадь кухни',
        'property_id' => 66,
      ),
      array (
        'field' => 'area_of_each_room',
        'name' => 'Площадь каждой комнаты',
        'property_id' => 67,
      ),
      array (
        'field' => 'about_count_bedrooms',
        'name' => 'Количество спален',
        'property_id' => 76,
      ),
      array (
        'field' => 'balconies',
        'name' => 'Кол-во балконов',
        'property_id' => 70,
      ),
      array (
        'field' => 'number_of_loggias',
        'name' => 'Кол-во лоджий',
        'property_id' => 71,
      ),
      array (
        'field' => 'passenger_elevators',
        'name' => 'Кол-во пасс. лифтов',
        'property_id' => 68,
      ),
      array (
        'field' => 'cargo_elevators',
        'name' => 'Кол-во груз. лифтов',
        'property_id' => 69,
      ),
      array (
        'field' => 'number_of_bathrooms_combined',
        'name' => 'Кол-во совм. с/у',
        'property_id' => 72,
      ),
      array (
        'field' => 'number_of_separate_toilets',
        'name' => 'Кол-во разд. с/у',
        'property_id' => 73,
      ),
      array (
        'field' => 'where_to_go_out_the_window',
        'name' => 'Куда выходят окна',
        'property_id' => 74,
      ),
      array (
        'field' => 'the_possibility_of_a_mortgage',
        'name' => 'Возможность ипотеки',
        'property_id' => 75,
      ),
      array (
        'field' => 'the_distance_from_the_metro_in_minutes',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'elitenew' => array (
    'base' => array (
      array (
        'field' => 'rooms',
        'name' => 'Количество комнат',
        'property_id' => 47,
        'use_for' => 'object',
      ),
      array (
        'field' => 'estate',
        'name' => 'Жилой комплекс',
        'property_id' => 2,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип дома',
        'property_id' => 48,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flats',
        'name' => 'Количество квартир',
        'property_id' => 49,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flatspaces',
        'name' => 'Площади квартир',
        'property_id' => 50,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'front',
        'name' => 'Фасад',
        'property_id' => 52,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'territory',
        'name' => 'Территория',
        'property_id' => 80,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'decorationtext',
        'name' => 'Отделка площадей общего пользования',
        'property_id' => 53,
        'use_for' => 'supobject',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция',
        'property_id' => 54,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 55,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'itp',
        'name' => 'Итп',
        'property_id' => 56,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна',
        'property_id' => 57,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'doors',
        'name' => 'Двери',
        'property_id' => 58,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'other',
        'name' => 'Прочее',
        'property_id' => 59,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_additional',
        'name' => 'Дополнительно',
        'property_id' => 60,
        'use_for' => 'supobject',
      ),
    ),
    'flat' => array (
      array (
        'field' => 'about_floorspace',
        'name' => 'Жилая площадь',
        'property_id' => 61,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'about_toilet',
        'name' => 'Количество санузлов',
        'property_id' => 62,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 77,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_balcony',
        'name' => 'Лоджии и балконы',
        'property_id' => 63,
        'use_for' => 'object',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'roomsfrom',
        'name' => 'Комнат от',
        'property_id' => 64,
      ),
      array (
        'field' => 'roomsto',
        'name' => 'Комнат до',
        'property_id' => 65,
      ),
      array (
        'field' => 'number_of_bathrooms_combined',
        'name' => 'Кол-во совм. с/у',
        'property_id' => 72,
      ),
      array (
        'field' => 'where_to_go_out_the_window',
        'name' => 'Вид из окна',
        'property_id' => 74,
      ),
      array (
        'field' => 'kitchen_area',
        'name' => 'Площадь кухни',
        'property_id' => 66,
      ),
      array (
        'field' => 'area_of_each_room',
        'name' => 'Площадь каждой комнаты',
        'property_id' => 67,
      ),
      array (
        'field' => 'balconies',
        'name' => 'Кол-во балконов',
        'property_id' => 70,
      ),
      array (
        'field' => 'number_of_loggias',
        'name' => 'Кол-во лоджий',
        'property_id' => 71,
      ),
      array (
        'field' => 'number_of_separate_toilets',
        'name' => 'Кол-во разд. с/у',
        'property_id' => 73,
      ),
      array (
        'field' => 'passenger_elevators',
        'name' => 'Кол-во пасс. лифтов',
        'property_id' => 68,
      ),
      array (
        'field' => 'cargo_elevators',
        'name' => 'Кол-во груз. лифтов',
        'property_id' => 69,
      ),
      array (
        'field' => 'the_distance_from_the_metro_in_minutes',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'the_possibility_of_a_mortgage',
        'name' => 'Возможность ипотеки',
        'property_id' => 75,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'flatrent' => array (
    'base' => array (
      array (
        'field' => 'rooms',
        'name' => 'Количество комнат',
        'property_id' => 47,
        'use_for' => 'object',
      ),
      array (
        'field' => 'estate',
        'name' => 'Жилой комплекс',
        'property_id' => 2,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'buildtype',
        'name' => 'Тип дома',
        'property_id' => 48,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'year',
        'name' => 'Год постройки',
        'property_id' => 6,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flats',
        'name' => 'Количество квартир',
        'property_id' => 49,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'flatspaces',
        'name' => 'Площади квартир',
        'property_id' => 50,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'parking',
        'name' => 'Количество машиномест',
        'property_id' => 51,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'front',
        'name' => 'Фасад',
        'property_id' => 52,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'territory',
        'name' => 'Территория',
        'property_id' => 80,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'decorationtext',
        'name' => 'Отделка площадей общего пользования',
        'property_id' => 53,
        'use_for' => 'supobject',
      ),
    ),
    'tech' => array (
      array (
        'field' => 'ventilation',
        'name' => 'Вентиляция',
        'property_id' => 54,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 55,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'itp',
        'name' => 'Итп',
        'property_id' => 56,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'lift',
        'name' => 'Лифты',
        'property_id' => 17,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'windows',
        'name' => 'Окна',
        'property_id' => 57,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'doors',
        'name' => 'Двери',
        'property_id' => 58,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'other',
        'name' => 'Прочее',
        'property_id' => 59,
        'use_for' => 'supobject',
      ),
    ),
    'infra' => array (
      array (
        'field' => 'infra_objects',
        'name' => 'Объекты инфраструктуры',
        'property_id' => 27,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_additional',
        'name' => 'Дополнительно',
        'property_id' => 60,
        'use_for' => 'supobject',
      ),
    ),
    'flat' => array (
      array (
        'field' => 'about_floorspace',
        'name' => 'Жилая площадь',
        'property_id' => 61,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_floor',
        'name' => 'Этаж',
        'property_id' => 9,
        'use_for' => 'object',
      ),
      array (
        'field' => 'roomheight',
        'name' => 'Высота потолков',
        'property_id' => 14,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_toilet',
        'name' => 'Количество санузлов',
        'property_id' => 62,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_conditioning',
        'name' => 'Кондиционирование',
        'property_id' => 77,
        'use_for' => 'object',
      ),
      array (
        'field' => 'about_balcony',
        'name' => 'Лоджии и балконы',
        'property_id' => 63,
        'use_for' => 'object',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'roomsfrom',
        'name' => 'Комнат от',
        'property_id' => 64,
      ),
      array (
        'field' => 'roomsto',
        'name' => 'Комнат до',
        'property_id' => 65,
      ),
      array (
        'field' => 'kitchen_area',
        'name' => 'Площадь кухни',
        'property_id' => 66,
      ),
      array (
        'field' => 'area_of_each_room',
        'name' => 'Площадь каждой комнаты',
        'property_id' => 67,
      ),
      array (
        'field' => 'balconies',
        'name' => 'Кол-во балконов',
        'property_id' => 70,
      ),
      array (
        'field' => 'number_of_loggias',
        'name' => 'Кол-во лоджий',
        'property_id' => 71,
      ),
      array (
        'field' => 'number_of_bathrooms_combined',
        'name' => 'Кол-во совм. с/у',
        'property_id' => 72,
      ),
      array (
        'field' => 'number_of_separate_toilets',
        'name' => 'Кол-во разд. с/у',
        'property_id' => 73,
      ),
      array (
        'field' => 'passenger_elevators',
        'name' => 'Кол-во пасс. лифтов',
        'property_id' => 68,
      ),
      array (
        'field' => 'about_count_bedrooms',
        'name' => 'Количество спален',
        'property_id' => 76,
      ),
      array (
        'field' => 'where_to_go_out_the_window',
        'name' => 'Куда выходят окна',
        'property_id' => 74,
      ),
      array (
        'field' => 'cargo_elevators',
        'name' => 'Кол-во груз. лифтов',
        'property_id' => 69,
      ),
      array (
        'field' => 'the_distance_from_the_metro_in_minutes',
        'name' => 'Удаленность от метро',
        'property_id' => 3,
      ),
      array (
        'field' => 'the_possibility_of_a_mortgage',
        'name' => 'Возможность ипотеки',
        'property_id' => 75,
      ),
      array (
        'field' => 'export_to_cian',
        'name' => 'Экспорт в ЦИАН',
        'property_id' => 81,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
  'outoftown' => array (
    'base' => array (
      array (
        'field' => 'price_land_from',
        'name' => 'Стоимость за сотку от',
        'property_id' => 82,
      ),
      array (
        'field' => 'price_land_to',
        'name' => 'Стоимость за сотку до',
        'property_id' => 83,
      ),
      array (
        'field' => 'distance_mkad',
        'name' => 'Удаленность от МКАД',
        'property_id' => 31,
      ),
      array (
        'field' => 'spaceplot',
        'name' => 'Площадь участка (сотки)',
        'property_id' => 22,
        'use_for' => 'object',
      ),
      array (
        'field' => 'space',
        'name' => 'Площадь дома (кв.м)',
        'property_id' => 33,
      ),
      array (
        'field' => 'under_construction',
        'name' => 'Готовность дома',
        'property_id' => 78,
        'use_for' => 'supobject',
      ),
    ),
    'about' => array (
      array (
        'field' => 'objecttype',
        'name' => 'Тип объекта',
        'property_id' => 1,
      ),
      array (
        'field' => 'construction',
        'name' => 'Конструкция дома',
        'property_id' => 34,
        'use_for' => 'object',
      ),
      array (
        'field' => 'arch_style',
        'name' => 'Архитектурный стиль',
        'property_id' => 35,
        'use_for' => 'object',
      ),
      array (
        'field' => 'floors',
        'name' => 'Количество этажей',
        'property_id' => 10,
        'use_for' => 'object',
      ),
      array (
        'field' => 'market',
        'name' => 'Рынок',
        'property_id' => 79,
        'use_for' => 'object',
        'authorized_only' => 1,
      ),
      array (
        'field' => 'decoration',
        'name' => 'Отделка',
        'property_id' => 8,
        'use_for' => 'object',
      ),
      array (
        'field' => 'infra_parking',
        'name' => 'Парковка',
        'property_id' => 26,
        'use_for' => 'object',
      ),
    ),
    'comm' => array (
      array (
        'field' => 'service_electricity',
        'name' => 'Электричество',
        'property_id' => 36,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_gas',
        'name' => 'Газоснабжение',
        'property_id' => 37,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_water',
        'name' => 'Водоснабжение',
        'property_id' => 38,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_drainage',
        'name' => 'Канализация',
        'property_id' => 39,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_inner',
        'name' => 'Внутридомовые коммуникации',
        'property_id' => 40,
        'use_for' => 'object',
      ),
      array (
        'field' => 'service_tele',
        'name' => 'Телекоммуникации',
        'property_id' => 41,
        'use_for' => 'object',
      ),
    ),
    'more' => array (
      array (
        'field' => 'infra_secur',
        'name' => 'Охрана и безопасность',
        'property_id' => 25,
        'use_for' => 'supobject',
      ),
      array (
        'field' => 'infra_accomplishment',
        'name' => 'Инфраструктура и окружение',
        'property_id' => 42,
        'use_for' => 'supobject',
      ),
    ),
    'hidden' => array (
      array (
        'field' => 'only_plot',
        'name' => 'Только участок',
        'property_id' => 32,
      ),
      array (
        'field' => 'locality',
        'name' => 'Населенный пункт',
        'property_id' => 43,
      ),
      array (
        'field' => 'cottageVillage',
        'name' => 'Коттеджный посёлок',
        'property_id' => 44,
      ),
      array (
        'field' => 'type_of_land',
        'name' => 'Категория земель',
        'property_id' => 45,
      ),
      array (
        'field' => 'district_of',
        'name' => 'Район области',
        'property_id' => 46,
      ),
      array (
        'field' => 'settlements_tba',
        'name' => 'Коттеджные поселки для ТБА',
        'property_id' => 88,
      ),
      array (
        'field' => 'premium_cian',
        'name' => 'Премиум размещение на ЦИАНЕ',
        'property_id' => 89,
      ),
    ),
  ),
),

  $_widget_properties = array(
    'comsell' => array(
      'objecttype' => array(
        'type' => 'choice',
        'values' => array(
          'Торговое помещение',
          'Офисное помещение',
          'Отдельно стоящее здание',
          'Готовый арендный бизнес',
          'Особняк',
          'Помещение свободного назначения',
          'Склад/складской комплекс',
          'Промышленный комплекс',
          'Земельный участок',
          'Прочее',
        )
      ),
      'decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'm_a_p_Currency' => array(
        'type' => 'choiceCurrency',
        'values' => array(
          'RUR',
          'USD',
          'EUR',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_services' => array(
        'type' => 'textarea',
      ),
    ),

    'comrent' => array(
      'objecttype' => array(
        'type' => 'choice',
        'values' => array(
          'Торговое помещение',
          'Офисное помещение',
          'Отдельно стоящее здание',
          'Готовый арендный бизнес',
          'Особняк',
          'Помещение свободного назначения',
          'Склад/складской комплекс',
          'Промышленный комплекс',
          'Земельный участок',
          'Прочее',
        )
      ),
      'decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'm_a_p_Currency' => array(
        'type' => 'choiceCurrency',
        'values' => array(
          'RUR',
          'USD',
          'EUR',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_services' => array(
        'type' => 'textarea',
      ),
    ),

    'cottage' => array(
      'objecttype' => array(
        'type' => 'choice',
        'values' => array(
          'Участок',
          'Таунхаус',
          'Квартира',
          'Коттедж',
          'Коттеджный поселок',
        )
      ),
      'decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_accomplishment' => array(
        'type' => 'textarea',
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'export_to_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
        )
      ),
    ),

    'outoftown' => array(
      'objecttype' => array(
        'type' => 'choice',
        'values' => array(
          'Участок',
          'Таунхаус',
          'Квартира',
          'Коттедж',
          'Коттеджный поселок',
        )
      ),
      'decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'infra_accomplishment' => array(
        'type' => 'textarea',
      ),
      'market' => array(
        'type' => 'choice',
        'values' => array(
          'Первичный',
          'Вторичный',
        ),
      ),
    ),

    'elitenew' => array(
      'about_balcony' => array(
        'type' => 'multichoice',
        'values' => array(
          'балкон',
          'лоджия',
          'терраса',
        )
      ),
      'about_decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'territory' => array(
        'type' => 'multichoice',
        'values' => array(
          'нет',
          'огорожена',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_additional' => array(
        'type' => 'textarea',
      ),
    ),

    'eliteflat' => array(
      'about_balcony' => array(
        'type' => 'multichoice',
        'values' => array(
          'балкон',
          'лоджия',
          'терраса',
        )
      ),
      'about_decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'territory' => array(
        'type' => 'multichoice',
        'values' => array(
          'нет',
          'огорожена',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_additional' => array(
        'type' => 'textarea',
      ),
      'market' => array(
        'type' => 'choice',
        'values' => array(
          'Первичный',
          'Вторичный',
        ),
      ),
    ),

    'penthouse' => array(
      'about_balcony' => array(
        'type' => 'multichoice',
        'values' => array(
          'балкон',
          'лоджия',
          'терраса',
        )
      ),
      'about_decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'territory' => array(
        'type' => 'multichoice',
        'values' => array(
          'нет',
          'огорожена',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_additional' => array(
        'type' => 'textarea',
      ),
      'market' => array(
        'type' => 'choice',
        'values' => array(
        ),
      ),
    ),

    'flatrent' => array(
      'about_balcony' => array(
        'type' => 'multichoice',
        'values' => array(
          'балкон',
          'лоджия',
          'терраса',
        )
      ),
      'about_decoration' => array(
        'type' => 'choice',
        'values' => array(
          'без отделки',
          'с отделкой',
        )
      ),
      'under_construction' => array(
        'type' => 'choice',
        'values' => array(
          'Строящийся',
          'Построен',
        )
      ),
      'infra_parking' => array(
        'type' => 'multichoice',
        'values' => array(
          'наземный паркинг',
          'подземный паркинг',
        )
      ),
      'premium_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
         )
      ),
      'territory' => array(
        'type' => 'multichoice',
        'values' => array(
          'нет',
          'огорожена',
        )
      ),
      'infra_secur' => array(
        'type' => 'textarea',
      ),
      'infra_objects' => array(
        'type' => 'textarea',
      ),
      'infra_additional' => array(
        'type' => 'textarea',
      ),
      'export_to_cian' => array(
        'type' => 'choice',
        'values' => array(
          'да',
          'нет',
        )
      ),
    ),
  ),


    $_listable_by_property = array(
      'comsell' => array(
        'objecttype' => array(
          'Торговое помещение',
          'Офисное помещение',
          'Отдельно стоящее здание',
          'Готовый арендный бизнес',
        ),

      ),
      'comrent' => array(
        'objecttype' => array(
          'Торговое помещение',
          'Офисное помещение',
          'Отдельно стоящее здание',
        ),
      ),
    ),

    $convert_array = array(63, 26, 80),
    $convert_boolean = array();
}
