<?php

/**
 * ParamTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParamTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object ParamTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Param');
  }

  public function match($string)
  {
    return $this->createQuery()
            ->select('id, name')
            ->andWhere('name LIKE ?', '%'.$string.'%')
            ->fetchArray();
  }
}