<?php

/**
 * PhotoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object PhotoTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Photo');
  }

  public function getRelatedPhotos($lot_id)
  {
    return $this->createQuery()
            ->where('lot_id = ?', $lot_id)
            ->orderBy('photo_type_id ASC, position ASC')
            ->execute();
  }

  public function getPhotosByLotIds($lot_ids)
  {
    if (empty($lot_ids)) return new Doctrine_Collection($this);

    return $this->createQuery()
            ->whereIn('lot_id', $lot_ids)
            ->orderBy('lot_id, photo_type_id ASC, position ASC')
            ->execute();
  }
}