<?php

/**
 * SeoTextTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeoTextTable extends Doctrine_Table
{
  private static $_hrurl_list;


  /**
   * Returns an instance of this class.
   *
   * @return object SeoTextTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('SeoText');
  }


  public function fetchHrurlByUrl($url)
  {
    $this->initHrurlsCache();
    return empty(self::$_hrurl_list[$url]) ? false : self::$_hrurl_list[$url];
  }


  private function initHrurlsCache()
  {
    if (is_null(self::$_hrurl_list)) {
      $cache = KreCache::getInstance();
      if ($cache->has(SeoText::CACHE_KEY_LIST_HRURL_BY_URL)) {
        self::$_hrurl_list = unserialize($cache->get(SeoText::CACHE_KEY_LIST_HRURL_BY_URL));
      }
      else {
        $query = $this->createQuery()
                ->select('url, hrurl')
                ->andWhere('hrurl IS NOT NULL')
                ->andWhere('hrurl <> ?', '');

        $data = array();
        foreach ($query->fetchArray() as $seo) {
          $data[$seo['url']] = $seo['hrurl'];
        }

        $cache->set(SeoText::CACHE_KEY_LIST_HRURL_BY_URL, serialize($data), 86400);
        self::$_hrurl_list = $data;
      }
    }
  }
}