<?php

/**
 * Vacancy
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kre
 * @subpackage model
 * @author     Garin Studio
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Vacancy extends BaseVacancy
{
  const DEFAULT_ID = 27;
  public static
    $_ids   = array(
      56   => 'city',
      57   => 'country',
      58   => 'commercial',
      59   => 'pr',
      8560 => 'internship',
    ),
    $_types = array(
      'city'      => 'Городская недвижимость',
      'country'   => 'Загородная недвижимость',
      'commercial'=> 'Коммерческая недвижимость',
      'pr'        => 'Маркетинг и PR',
      'internship'=> 'Стажировка',
      //If you want to add new type, don't forget alter schema.yml too.
    );


  public function getTypeText()
  {
    return self::$_types[$this->_get('type')];
  }

  public static function getTypeById($id) {
    return !empty(self::$_ids[$id]) ? self::$_ids[$id] : null;
  }

  public static function getIdByType($type) {
    return null !== $type && in_array($type, self::$_ids) ? array_search($type,self::$_ids) : self::DEFAULT_ID;
  }
}