all:
  stylesheets:
    - /sfAdminThemejRollerPlugin/css/reset.css
    - /sfAdminThemejRollerPlugin/css/jquery/redmond/jquery-ui.custom.css
    - /sfAdminThemejRollerPlugin/css/jroller.css
    - /sfAdminThemejRollerPlugin/css/fg.menu.css
    - http://kre.server.garin.su/sfFormExtraPlugin/css/jquery.autocompleter.css
  javascripts:
    - /sfAdminThemejRollerPlugin/js/jquery.min.js
    - /sfAdminThemejRollerPlugin/js/jquery-ui.custom.min.js
    - /sfAdminThemejRollerPlugin/js/fg.menu.js
    - /sfAdminThemejRollerPlugin/js/jroller.js
    - http://kre.server.garin.su/sfFormExtraPlugin/js/jquery.autocompleter.js