all:
  yandex_key: ALtGDVABAAAA-cdgFwIAKL1ijusS_iNffLGieKHKvwVaWd0AAAAAAAAAAACFYypGVIy7e6o56BdIcuGu1wBlFg==
  default_title: 'Элитная недвижимость Москвы| Агентство элитной недвижимости CONTACT Real Estate'
  default_description: 'Продажа элитной недвижимости в Москве и Подмосковье. От роскошного пентхауса – до коттеджа в элитном поселке. Услуги для покупателя без комиссии.'
  default_keywords: ''
  contact_email: Cherednikov.roman@gmail.com
  order_catalog_email: Cherednikov.roman@gmail.com
  watermark: /web/images/watermark.png
  phones:
    office: '(495) 956-77-99'
    office_comsell: '(495) 956-37-97'
    office_comrent: '(495) 956-37-97'
    office_cottage: '(495) 956-60-56'
    office_outoftown: '(495) 956-60-56'
    office_eliteflat: '(495) 956-77-99'
    office_elitenew: '(495) 956-77-99'
    office_penthouse: '(495) 956-77-99'
    office_flatrent: '(495) 956-77-99'
  claim:
    emails:
      1: Cherednikov.roman@gmail.com
      2: cherednikov.alex@gmail.com
      3: cherednikov.al.ex@gmail.com
      4: Cherednikov.roman@gmail.com
      5: Cherednikov.roman@gmail.com
      6: Cherednikov.roman@gmail.com
      7: Cherednikov.roman@gmail.com
      8: Cherednikov.roman@gmail.com
      9: Cherednikov.roman@gmail.com
      10: Cherednikov.roman@gmail.com
      11: Cherednikov.roman@gmail.com
      12: Cherednikov.roman@gmail.com
  default_spec_text: '<p>Текст по-умолчанию для спецпредложений на главной!</p>'
  csstat_menu:
    broker:
      object: Объекты
      logout: Выход
    manager:
      object: Объекты
      broker: Брокеры
      query: 'Поисковые запросы'
      recommendation: 'Переходы из рекомендаций'
      logout: Выход
  cache:
    #class: sfMemcacheCache
    #params:
      ##host: 'unix:///new.kre.ru/memcached.sock'
      ##port: 0
      #host: 127.0.0.1
      #port: 11211
      #automatic_cleaning_factor: 1
      #lifetime: 86400
    class: sfFileCache
    params:
      automatic_cleaning_factor: 1
      cache_dir: '%SF_CACHE_DIR%/kre'
      lifetime: 86400
      prefix: '%SF_APP_DIR%/cache_kree'

  .array:
    districts:
      1: 'Арбат'
      2: 'Патриаршие пруды'
      3: 'Тверской'
      4: 'Сретенка'
      5: 'Чистые пруды'
      6: 'Таганский'
      7: 'Замоскворечье'
      8: 'Якиманка'
      9: 'Остоженка'
      10: 'Китай город'
      11: 'Плющиха'
      12: 'Хамовники'
      13: 'Пресненский'
      14: 'Москва Сити'
      15: 'Новослободский'
      16: 'Мещанский'
      17: 'Басманный'
      18: 'Донской'
      19: 'Даниловский'
      20: 'Северо-Западный АО'
      21: 'Северный АО'
      22: 'Северо-Восточный АО'
      23: 'Восточный АО'
      24: 'Юго-Восточный АО'
      25: 'Южный АО'
      26: 'Юго-Западный АО'
      28: 'Западный АО'
      30: 'Воробьевы горы'
      31: 'Красносельский'
      32: 'Зеленоградский АО'

    subways:
      - Авиамоторная
      - Автозаводская
      - 'Улица Академика Янгеля'
      - Академическая
      - 'Александровский сад'
      - Алексеевская
      - Алтуфьево
      - Аннино
      - Арбатская
      - Аэропорт
      - Бабушкинская
      - Багратионовская
      - Баррикадная
      - Бауманская
      - Беговая
      - Белорусская
      - Беляево
      - Бибирево
      - 'Библиотека им. Ленина'
      - 'Битцевский парк'
      - Боровицкая
      - 'Ботанический сад'
      - 'Бульвар Дмитрия Донского'
      - Братиславская
      - Варшавская
      - ВДНХ
      - Владыкино
      - 'Водный стадион'
      - Войковская
      - 'Волгоградский проспект'
      - Волжская
      - 'Воробьевы горы'
      - Выхино
      - Динамо
      - Дмитровская
      - Добрынинская
      - Домодедовская
      - Дубровка
      - Измайловская
      - Партизанская
      - Калужская
      - Кантемировская
      - Каховская
      - Каширская
      - Киевская
      - Китай-Город
      - Кожуховская
      - Коломенская
      - Комсомольская
      - Коньково
      - Красногвардейская
      - Краснопресненская
      - Красносельская
      - 'Красные ворота'
      - Кропоткинская
      - Крылатское
      - 'Кузнецкий Мост'
      - Кузьминки
      - Кунцевская
      - Курская
      - Кутузовская
      - 'Ленинский проспект'
      - Лубянка
      - Люблино
      - Марьино
      - Маяковская
      - Медведково
      - Менделеевская
      - Молодежная
      - Нагатинская
      - Нагорная
      - 'Нахимовский проспект'
      - Новогиреево
      - Новокузнецкая
      - Новослободская
      - 'Новые Черемушки'
      - Октябрьская
      - 'Октябрьское поле'
      - Орехово
      - Отрадное
      - 'Охотный ряд'
      - Павелецкая
      - 'Парк Культуры'
      - 'Парк победы'
      - Первомайская
      - Перово
      - Петровско-Разумовская
      - Печатники
      - Пионерская
      - Планерная
      - 'Площадь Ильича'
      - 'Площадь революции'
      - Полежаевская
      - Полянка
      - Пражская
      - 'Преображенская пл.'
      - Пролетарская
      - 'Проспект Вернадского'
      - 'Проспект Мира'
      - Профсоюзная
      - Пушкинская
      - 'Речной вокзал'
      - Рижская
      - 'Рязанский проспект'
      - Савеловская
      - Свиблово
      - Севастопольская
      - Семеновская
      - Серпуховская
      - Смоленская
      - Сокол
      - Сокольники
      - Спортивная
      - Студенческая
      - Сухаревская
      - Сходненская
      - Таганская
      - Тверская
      - Театральная
      - Текстильщики
      - 'Теплый стан'
      - Тимирязевская
      - Третьяковская
      - Тульская
      - Тургеневская
      - Тушинская
      - 'Улица 1905 года'
      - 'Улица Подбельского'
      - Университет
      - 'Филевский парк'
      - Фили
      - Фрунзенская
      - Царицыно
      - 'Цветной бульвар'
      - Черкизовская
      - Чертановская
      - Чеховская
      - 'Чистые пруды'
      - Чкаловская
      - Шаболовская
      - 'Шоссе Энтузиастов'
      - Щелковская
      - Щукинская
      - Электрозаводская
      - Юго-западная
      - Южная
      - Ясенево
      - Выставочная
      - Международная
      - 'Сретенский бульвар'
      - Трубная
      - 'Славянский бульвар'
      - 'Марьина роща'
      - Достоевская
      - Мякинино
      - 'Пятницкое шоссе'
      - Митино

    wards:
      1: Алтуфьевское
      2: Боровское
      3: Варшавское
      4: Волоколамское
      5: Горьковское
      6: Дмитровское
      7: Егорьевское
      8: Ильинское
      9: Калужское
      10: Каширское
      11: Киевское
      12: Куркинское
      13: Ленинградское
      14: Минское
      15: Можайское
      16: Новорижское
      17: Новорязанское
      18: Носовихинское
      19: Осташковское
      20: Пятницкое
      21: Рогачевское
      22: Рублево-Успенское
      23: Рязанское
      24: Симферопольское
      25: Сколковское
      26: Щелковское
      27: Ярославское
    search_presets:
      districts: { 1: arbat, 2: patriarshie_prudy, 3: tverskoy, 4: sretenka, 5: chistie_prudy, 6: taganskij, 7: zamoskvorechie, 8: yakimanka, 9: ostozhenka, 10: kitay_gorod, 11: pluschiha, 12: hamovniky, 13: presnenskij, 14: moscow_city, 15: novoslobodskij, 16: meschanskij, 17: basmannij, 18: donskoy, 19: danilovskij, 20: szao, 21: sao, 22: svao, 23: vao, 24: uvao, 25: uao, 26: uzao, 28: zao, 30: vorobyovy_gory }
      wards: { 1: altufevskoe, 2: borovskoe, 3: varshavskoe, 4: volokolamskoe, 5: gorkovskoe, 6: dmitrovskoe, 7: egorevskoe, 8: ilinskoe, 9: kaluzhskoe, 10: kashirskoe, 11: kievskoe, 12: kurkinskoe, 13: leningradskoe, 14: minskoe, 15: mozhaiskoe, 16: novorizhskoe, 17: novoryazanskoe, 18: nosovihinskoe, 19: ostashkovskoe, 20: pjatnickoe, 21: rogachevskoe, 22: rublevo_uspenskoe, 23: rjazanskoe, 24: simferopolskoe, 25: skolkovskoe, 26: schelkovskoe, 27: yaroslavskoe }
      objecttype: { 'Торговое помещение': torgovoe_pomecshenie, 'Офисное помещение': ofisnoe_pomeschenie, 'Отдельно стоящее здание': otdelno_stoyaschee_zdanie, 'Готовый арендный бизнес': gotovij_arendnij_biznes }

  title_hc:
    news8235: 'Новые объекты на корпоративном сайте 2009'
    offersoutoftown6115: 'ИСКЛЮЧИТЕЛЬНОЕ предложение на берегу Истринского водохранилища в Экопоселке «Полуостров»'
    offersoutoftownpoluostrov6114: 'Земельные участки в Экопоселкe «Полуостров» на берегу Истринского водохранилища'
    offersoutoftown5385: 'Новоглаголево. Участки без подряда на строительство'
    analytics: 'Обзор рынка 2014'
    analytics6archive2013: 'Обзор рынка 2013'

  presets_h1:
    eliteflat:
      _main: 'Продажа элитных квартир в Москве'
      ostozhenka: 'Элитные квартиры на Остоженке'
      arbat: 'Элитные квартиры на Арбате'
      patriarshie_prudy: 'Элитные квартиры на Патриарших прудах'
      kitay_gorod: 'Элитные квартиры в районе Китай-город'
      tverskoy: 'Элитные квартиры на Тверской'
      yakimanka: 'Элитные квартиры на Якиманке'
      pluschiha: 'Элитные квартиры на Плющихе'
      sretenka: 'Элитные квартиры на Сретенке'
      zamoskvorechie: 'Элитные квартиры в Замоскворечье'
      novoslobodskij: 'Элитные квартиры в Новослободском районе'
      chistie_prudy: 'Элитные квартиры на Чистых прудах'
      hamovniky: 'Элитные квартиры в Хамовниках'
      taganskij: 'Элитные квартиры на Таганке'
      moscow_city: 'Апартаменты в Москва Сити'
      presnenskij: 'Элитные квартиры на Пресне'
      meschanskij: 'Элитные квартиры в Мещанском районе'
      zao: 'Элитные квартиры в Западном АО'
      basmannij: 'Элитные квартиры в Басманном районе'
      donskoy: 'Элитные квартиры в Донском районе'
      uao: 'Элитные квартиры в Южном АО'
      uzao: 'Элитные квартиры в Юго-Западном АО'
      danilovskij: 'Элитные квартиры в Даниловском районе'
      szao: 'Элитные квартиры в Северо-Западном АО'
      sao: 'Элитные квартиры в Северном АО'
      svao: 'Элитные квартиры в Северо-Восточном АО'
      vao: 'Элитные квартиры в Восточном АО'
      uvao: 'Элитные квартиры в Юго-Восточном АО'
      gagarinskij: 'Элитные квартиры в Гагаринском районе'
      zelao: 'Элитные квартиры в Зеленоградском АО'
      vorobyovy_gory: 'Элитные квартиры на Воробьёвых горах'
    elitenew:
      _main: 'Продажа элитных новостроек в жилых комплексах Москвы'
      ostozhenka: 'Элитные новостройки на Остоженке'
      arbat: 'Элитные новостройки на Арбате'
      patriarshie_prudy: 'Элитные новостройки на Патриарших прудах'
      kitay_gorod: 'Элитные новостройки в районе Китай-город'
      tverskoy: 'Элитные новостройки на Тверской'
      yakimanka: 'Элитные новостройки на Якиманке'
      pluschiha: 'Элитные новостройки на Плющихе'
      sretenka: 'Элитные новостройки на Сретенке'
      zamoskvorechie: 'Элитные новостройки в Замоскворечье'
      novoslobodskij: 'Элитные новостройки в Новослободском районе'
      chistie_prudy: 'Элитные новостройки на Чистых прудах'
      hamovniky: 'Элитные новостройки в Хамовниках'
      taganskij: 'Элитные новостройки на Таганке'
      moscow_city: 'Башни Москва Сити'
      presnenskij: 'Элитные новостройки на Пресне'
      meschanskij: 'Элитные новостройки в Мещанском районе'
      zao: 'Элитные новостройки в Западном АО'
      basmannij: 'Элитные новостройки в Басманном районе'
      donskoy: 'Элитные новостройки в Донском районе'
      uao: 'Элитные новостройки в Южном АО'
      uzao: 'Элитные новостройки в Юго-Западном АО'
      danilovskij: 'Элитные новостройки в Даниловском районе'
      szao: 'Элитные новостройки в Северо-Западном АО'
      sao: 'Элитные новостройки в Северном АО'
      svao: 'Элитные новостройки в Северо-Восточном АО'
      vao: 'Элитные новостройки в Восточном АО'
      uvao: 'Элитные новостройки в Юго-Восточном АО'
      gagarinskij: 'Элитные новостройки в Гагаринском районе'
      zelao: 'Элитные новостройки в Зеленоградском АО'
      vorobyovy_gory: 'Элитные новостройки на Воробьёвых горах'
    penthouse:
      _main: 'Продажа пентхаусов в Москве'
      ostozhenka: 'Пентхаусы на Остоженке'
      arbat: 'Пентхаусы на Арбате'
      patriarshie_prudy: 'Пентхаусы на Патриарших прудах'
      kitay_gorod: 'Пентхаусы в районе Китай-город'
      tverskoy: 'Пентхаусы на Тверской'
      yakimanka: 'Пентхаусы на Якиманке'
      pluschiha: 'Пентхаусы на Плющихе'
      sretenka: 'Пентхаусы на Сретенке'
      zamoskvorechie: 'Пентхаусы в Замоскворечье'
      novoslobodskij: 'Пентхаусы в Новослободском районе'
      chistie_prudy: 'Пентхаусы на Чистых прудах'
      hamovniky: 'Пентхаусы в Хамовниках'
      taganskij: 'Пентхаусы на Таганке'
      moscow_city: 'Пентхаусы в Москва Сити'
      presnenskij: 'Пентхаусы на Пресне'
      meschanskij: 'Пентхаусы в Мещанском районе'
      zao: 'Пентхаусы в Западном АО'
      basmannij: 'Пентхаусы в Басманном районе'
      donskoy: 'Пентхаусы в Донском районе'
      uao: 'Пентхаусы в Южном АО'
      uzao: 'Пентхаусы в Юго-Западном АО'
      danilovskij: 'Пентхаусы в Даниловском районе'
      szao: 'Пентхаусы в Северо-Западном АО'
      sao: 'Пентхаусы в Северном АО'
      svao: 'Пентхаусы в Северо-Восточном АО'
      vao: 'Пентхаусы в Восточном АО'
      uvao: 'Пентхаусы в Юго-Восточном АО'
      gagarinskij: 'Пентхаусы в Гагаринском районе'
      zelao: 'Пентхаусы в Зеленоградском АО'
      vorobyovy_gory: 'Пентхаусы на Воробьёвых горах'
    flatrent:
      _main: 'Аренда элитных квартир (апартаментов) в Москве'
      ostozhenka: 'Аренда квартир на Остоженке'
      arbat: 'Аренда квартир на Арбате'
      patriarshie_prudy: 'Аренда квартир на Патриарших прудах'
      kitay_gorod: 'Аренда квартир в районе Китай-город'
      tverskoy: 'Аренда квартир на Тверской'
      yakimanka: 'Аренда квартир на Якиманке'
      pluschiha: 'Аренда квартир на Плющихе'
      sretenka: 'Аренда квартир на Сретенке'
      zamoskvorechie: 'Аренда квартир в Замоскворечье'
      novoslobodskij: 'Аренда квартир в Новослободском районе'
      chistie_prudy: 'Аренда квартир на Чистых прудах'
      hamovniky: 'Аренда квартир в Хамовниках'
      taganskij: 'Аренда квартир на Таганке'
      moscow_city: 'Аренда апартаментов в Москва Сити'
      presnenskij: 'Аренда квартир на Пресне'
      meschanskij: 'Аренда квартир в Мещанском районе'
      zao: 'Аренда квартир в Западном АО'
      basmannij: 'Аренда квартир в Басманном районе'
      donskoy: 'Аренда квартир в Донском районе'
      uao: 'Аренда квартир в Южном АО'
      uzao: 'Аренда квартир в Юго-Западном АО'
      danilovskij: 'Аренда квартир в Даниловском районе'
      szao: 'Аренда квартир в Северо-Западном АО'
      sao: 'Аренда квартир в Северном АО'
      svao: 'Аренда квартир в Северо-Восточном АО'
      vao: 'Аренда квартир в Восточном АО'
      uvao: 'Аренда квартир в Юго-Восточном АО'
      gagarinskij: 'Аренда квартир в Гагаринском районе'
      zelao: 'Аренда квартир в Зеленоградском АО'
      vorobyovy_gory: 'Аренда квартир на Воробьёвых горах'
    outoftown:
      _main: 'Продажа загородных домов, коттеджных поселков, участков в Подмосковье'
      rublevo_uspenskoe: 'Коттеджи и дома на Рублево-Успенском шоссе'
      novorizhskoe: 'Коттеджи и таунхаусы на Новорижском шоссе'
      ilinskoe: 'Коттеджи на Ильинском шоссе'
      minskoe: 'Коттеджи на Минском шоссе'
      mozhaiskoe: 'Коттеджи на Можайском шоссе'
      skolkovskoe: 'Коттеджи на Сколковском шоссе'
      kievskoe: 'Коттеджи и таунхаусы на Киевском шоссе'
      kaluzhskoe: 'Коттеджи по Калужскому шоссе'
      kurkinskoe: 'Коттеджи на Куркинском шоссе '
      dmitrovskoe: 'Коттеджи на Дмитровском шоссе'
      yaroslavskoe: 'Коттеджи на Ярославском шоссе'
      ostashkovskoe: 'Коттеджи на Осташковском шоссе'
      altufevskoe: 'Коттеджи на Алтуфьевском шоссе'
      borovskoe: 'Коттеджи на Боровском шоссе'
      varshavskoe: 'Коттеджи на Варшавском шоссе'
      volokolamskoe: 'Коттеджи на Волоколамском шоссе'
      gorkovskoe: 'Коттеджи на Горьковском шоссе'
      egorevskoe: 'Коттеджи на Егорьевском шоссе'
      kashirskoe: 'Коттеджи на Каширском шоссе'
      leningradskoe: 'Коттеджи на Ленинградском шоссе'
      novoryazanskoe: 'Коттеджи на Новорязанском шоссе'
      nosovihinskoe: 'Коттеджи на Носовихинском шоссе'
      pjatnickoe: 'Коттеджи на Пятницком шоссе'
      rogachevskoe: 'Коттеджи на Рогачевском шоссе'
      rjazanskoe: 'Коттеджи на Рязанском шоссе'
      simferopolskoe: 'Коттеджи на Симферопольском шоссе'
      schelkovskoe: 'Коттеджи на Щелковском шоссе'
    cottage:
      _main: 'Аренда элитных коттеджей в Подмосковье'
      rublevo_uspenskoe: 'Аренда коттеджа на Рублево – Успенском шоссе'
      novorizhskoe: 'Аренда коттеджей на Новорижском шоссе'
      ilinskoe: 'Аренда коттеджей на Ильинском шоссе'
      minskoe: 'Аренда коттеджей на Минском шоссе'
      mozhaiskoe: 'Аренда коттеджей на Можайском шоссе'
      skolkovskoe: 'Аренда коттеджей на Сколковском шоссе'
      kievskoe: 'Аренда коттеджей на Киевском шоссе '
      kaluzhskoe: 'Аренда коттеджей на Калужском шоссе'
      kurkinskoe: 'Аренда коттеджей на Куркинском шоссе '
      dmitrovskoe: 'Аренда коттеджей на Дмитровском шоссе'
      yaroslavskoe: 'Аренда коттеджей на Ярославском шоссе'
      ostashkovskoe: 'Аренда коттеджей на Осташковском шоссе'
      altufevskoe: 'Аренда коттеджей на Алтуфьевском шоссе'
      borovskoe: 'Аренда коттеджей на Боровском шоссе'
      varshavskoe: 'Аренда коттеджей на Варшавском шоссе'
      volokolamskoe: 'Аренда коттеджей на Волоколамском шоссе'
      gorkovskoe: 'Аренда коттеджей на Горьковском шоссе'
      egorevskoe: 'Аренда коттеджей на Егорьевском шоссе'
      kashirskoe: 'Аренда коттеджей на Каширском шоссе'
      leningradskoe: 'Аренда коттеджей на Ленинградском шоссе'
      novoryazanskoe: 'Аренда коттеджей на Новорязанском шоссе'
      nosovihinskoe: 'Аренда коттеджей на Носовихинском шоссе'
      pjatnickoe: 'Аренда коттеджей на Пятницком шоссе'
      rogachevskoe: 'Аренда коттеджей на Рогачевском шоссе'
      rjazanskoe: 'Аренда коттеджей на Рязанском шоссе'
      simferopolskoe: 'Аренда коттеджей на Симферопольском шоссе'
      schelkovskoe: 'Аренда коттеджей на Щелковском шоссе'
    comsell:
      _main: 'Продажа коммерческой недвижимости в Москве'
      torgovoe_pomecshenie: 'Продажа торговых помещений'
      ofisnoe_pomeschenie: 'Продажа офисов в Москве'
      otdelno_stoyaschee_zdanie: 'Продажа зданий в Москве'
      gotovij_arendnij_biznes: 'Продажа арендного бизнеса '
    comrent:
      _main: 'Аренда коммерческой недвижимости в Москве'
      torgovoe_pomecshenie: 'Аренда торговых помещений в Москве'
      ofisnoe_pomeschenie: 'Аренда офисов в центре Москвы'
      otdelno_stoyaschee_zdanie: 'Аренда зданий в Москве'