<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('lot_param', 'param_type_id', 'varchar', '15', array(
             ));
    }

    public function down()
    {

    }
}