<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('lot_param', 'lot_param_lot_id_lot_id');
        $this->dropForeignKey('lot_param', 'lot_param_param_id_param_id');
        $this->dropForeignKey('photo', 'photo_lot_id_lot_id');
        $this->createForeignKey('lot_param', 'lot_param_lot_id_lot_id_1', array(
             'name' => 'lot_param_lot_id_lot_id_1',
             'local' => 'lot_id',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('lot_param', 'lot_param_param_id_param_id_1', array(
             'name' => 'lot_param_param_id_param_id_1',
             'local' => 'param_id',
             'foreign' => 'id',
             'foreignTable' => 'param',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('photo', 'photo_lot_id_lot_id_1', array(
             'name' => 'photo_lot_id_lot_id_1',
             'local' => 'lot_id',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('lot_param', 'lot_param_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
        $this->addIndex('lot_param', 'lot_param_param_id', array(
             'fields' => 
             array(
              0 => 'param_id',
             ),
             ));
        $this->addIndex('photo', 'photo_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('lot_param', 'lot_param_lot_id_lot_id', array(
             'name' => 'lot_param_lot_id_lot_id',
             'local' => 'lot_id',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             ));
        $this->createForeignKey('lot_param', 'lot_param_param_id_param_id', array(
             'name' => 'lot_param_param_id_param_id',
             'local' => 'param_id',
             'foreign' => 'id',
             'foreignTable' => 'param',
             ));
        $this->createForeignKey('photo', 'photo_lot_id_lot_id', array(
             'name' => 'photo_lot_id_lot_id',
             'local' => 'lot_id',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             ));
        $this->dropForeignKey('lot_param', 'lot_param_lot_id_lot_id_1');
        $this->dropForeignKey('lot_param', 'lot_param_param_id_param_id_1');
        $this->dropForeignKey('photo', 'photo_lot_id_lot_id_1');
        $this->removeIndex('lot_param', 'lot_param_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
        $this->removeIndex('lot_param', 'lot_param_param_id', array(
             'fields' => 
             array(
              0 => 'param_id',
             ),
             ));
        $this->removeIndex('photo', 'photo_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
    }
}