<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'show_phone', 'enum', '', array(
             'values' => 
             array(
              0 => 'both',
              1 => 'broker',
              2 => 'office',
             ),
             'default' => 'both',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'show_phone');
    }
}