<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'ward', 'integer', '1', array(
             'unsigned' => '1',
             ));
        $this->addColumn('lot', 'ward2', 'integer', '1', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'ward');
        $this->removeColumn('lot', 'ward2');
    }
}