<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('lot', 'lot_pid_lot_id');
    }

    public function down()
    {
        $this->createForeignKey('lot', 'lot_pid_lot_id', array(
             'name' => 'lot_pid_lot_id',
             'local' => 'pid',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
    }
}