<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('vacancy', array(
      'id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'primary' => true,
        'autoincrement' => true,
        'length' => 2,
      ),
      'type' => array(
        'type' => 'enum',
        'values' => array('city','country','commercial','pr'),
        'notnull' => true,
        'length' => null,
      ),
      'name' => array(
        'type' => 'string',
        'notnull' => true,
        'length' => 150,
      ),
      'description' => array(
        'type' => 'clob',
        'notnull' => true,
        'length' => 65532,
      ),
      'email' => array(
        'type' => 'string',
        'notnull' => true,
        'email' => array('check_mx' => false),
        'length' => 50,
      ),
      'phone' => array(
        'type' => 'string',
        'length' => 50,
      ),
      'fio' => array(
        'type' => 'string',
        'length' => 50,
      ),
    ), array(
      'type' => 'InnoDB',
      'primary' =>
      array('id'),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down()
  {
    $this->dropTable('vacancy');
  }
}