<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('broker', 'login', array(
             'fields' => 
             array(
              0 => 'login',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('broker', 'email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('broker', 'login', array(
             'fields' => 
             array(
              0 => 'login',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('broker', 'email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'type' => 'unique',
             ));
    }
}