<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('broker', 'role', 'enum', '', array(
             'values' => 
             array(
              0 => 'broker',
              1 => 'manager',
             ),
             'notnull' => '1',
             ));
        $this->addColumn('broker', 'email', 'string', '128', array(
             ));
        $this->addColumn('broker', 'login', 'string', '64', array(
             ));
        $this->addColumn('broker', 'password', 'string', '40', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('broker', 'role');
        $this->removeColumn('broker', 'email');
        $this->removeColumn('broker', 'login');
        $this->removeColumn('broker', 'password');
    }
}