<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'active',
              1 => 'hidden',
              2 => 'inactive',
             ),
             'notnull' => '1',
             'default' => 'hidden',
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'status');
    }
}