<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('query', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'day' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'params' => 
             array(
              'type' => 'array',
              'length' => '',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'login' => 
              array(
              'fields' => 
              array(
               0 => 'day',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('query');
    }
}