<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'special_text', 'text');
        $this->addColumn('lot', 'is_special', 'boolean', null, array(
          'default' => '0',
          'notnull' => '1',
        ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'special_text');
        $this->removeColumn('lot', 'is_special');
    }
}