<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('claim', array(
          'id' =>
          array(
           'type' => 'integer',
           'unsigned' => true,
           'primary' => true,
           'autoincrement' => true,
           'length' => 2,
          ),
          'types' =>
          array(
           'type' => 'array',
           'notnull' => false,
           'length' => NULL,
          ),
          'lot_id' =>
          array(
           'type' => 'integer',
           'unsigned' => true,
           'notnull' => false,
           'length' => 8,
          ),
          'fio' =>
          array(
           'type' => 'string',
           'notnull' => true,
           'length' => 150,
          ),
          'email' =>
          array(
           'type' => 'string',
           'notnull' => true,
           'email' =>
           array(
           'check_mx' => false,
           ),
           'length' => 150,
          ),
          'phone' =>
          array(
           'type' => 'string',
           'notnull' => true,
           'length' => 50,
          ),
          'description' =>
          array(
           'type' => 'string',
           'length' => 1000,
          ),
          'status' =>
          array(
           'type' => 'enum',
           'values' =>
           array(
           0 => 'new',
           1 => 'resolved',
           2 => 'rejected'
           ),
           'length' => NULL,
          ),
          'created_at' =>
          array(
           'notnull' => true,
           'type' => 'timestamp',
           'length' => 25,
          ),
          'updated_at' =>
          array(
           'notnull' => true,
           'type' => 'timestamp',
           'length' => 25,
          ),
          ), array(
          'type' => 'InnoDB',
          'indexes' =>
          array(
          ),
          'primary' =>
          array(
           0 => 'id',
          ),
          'collate' => 'utf8_general_ci',
          'charset' => 'utf8',
          ));
    }

    public function down()
    {
        $this->dropTable('claim');
    }
}