<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
  
  public function up()
  {
    $this->createTable('seo_text', array(
      'id' => 
      array(
       'type' => 'integer',
       'unsigned' => true,
       'primary' => true,
       'autoincrement' => true,
       'length' => 4,
      ),
      'url' => 
      array(
       'type' => 'string',
       'notnull' => true,
       'length' => 250,
      ),
      'name' => 
      array(
       'type' => 'string',
       'notnull' => true,
       'length' => 250,
      ),
      'text' => 
      array(
       'type' => 'clob',
       'notnull' => true,
       'length' => 65532,
      ),
      ), array(
        'type' => 'InnoDB',
        'indexes' => 
        array(
         'url_index' => 
         array(
         'fields' => 
         array(
          0 => 'url',
         ),
         'type' => 'unique',
         ),
        ),
        'primary' => 
        array(
         0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      ));
  }

  public function down()
  {
    $this->dropTable('seo_text');
  }
}