<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->removeIndex('lot', 'type_url', array(
      'fields' =>
      array(
        0 => 'type',
        1 => 'url_id',
      ),
      'type' => 'unique',
    ));
    $this->removeColumn('lot', 'url_id');
  }

  public function down()
  {
    $this->addColumn('lot', 'url_id', 'integer', '8', array(
      'unsigned' => '1',
      'notnull' => '1',
    ));
    $this->addIndex('lot', 'type_url', array(
      'fields' =>
      array(
        0 => 'type',
        1 => 'url_id',
      ),
      'type' => 'unique',
    ));
  }
}