<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
  public function up()
  { 
    $this->addColumn('seo_text', 'description', 'string', 500, array(
      'notnull' => false
    ));
    $this->addColumn('seo_text', 'keywords', 'string', 500, array(
      'notnull' => false
    ));
  }

  public function down()
  {
    $this->removeColumn('seo_text', 'description');
    $this->removeColumn('seo_text', 'keywords');
  }
}