<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('lot_param', 'value', 'string', '500', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}