<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('broker', 'hidden', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('broker', 'hidden');
    }
}