<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'shortcut', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'shortcut');
    }
}