<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('vacancy', 'type', 'enum', '', array(
      'values'  =>
      array(
        0 => 'city',
        1 => 'country',
        2 => 'commercial',
        3 => 'pr',
        4 => 'internship',
      ),
      'notnull' => '1',
    ));
  }

  public function down()
  {
    $this->changeColumn('vacancy', 'type', 'enum', '', array(
      'values'  =>
      array(
        0 => 'city',
        1 => 'country',
        2 => 'commercial',
        3 => 'pr',
      ),
      'notnull' => '1',
    ));
  }
}