<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {      
        $this->addColumn('seo_text', 'title', 'string', '250', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {        
        $this->removeColumn('seo_text', 'title');
    }
}