<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {        
        $this->changeColumn('seo_text', 'url', 'clob', '65532', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('seo_text', 'url', 'string', '250', array(
             'notnull' => '1',
             ));
    }
}