<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addIndex('lot', 'type', array('fields' => array('type')));
    $this->addIndex('lot', 'status', array('fields' => array('status')));
  }

  public function down()
  {
    $this->removeIndex('lot', 'type', array('fields' => array('type')));
    $this->removeIndex('lot', 'status', array('fields' => array('status')));
  }

}