<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('lot', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->removeColumn('lot', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }
}