<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'priority', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'priority');
    }
}