<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
      $sql = 'INSERT INTO `param` (`id`, `name`) VALUES ("88", "Коттеджные поселки для ТБА")';
      Doctrine_Manager::connection()->exec($sql);
    }
    
    public function down()
    {
      $sql = 'DELETE FROM `param` WHERE `param`.`id` = 88';
      Doctrine_Manager::connection()->exec($sql);
    }
}