<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version49 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('lot_log', array(
      'id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'primary' => true,
        'autoincrement' => true,
        'length' => 8,
      ),
      'lot_id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'notnull' => true,
        'length' => 8,
      ),
      'modifications' => array(
        'type' => 'array',
        'notnull' => true,
      ),
      'created_by' => array(
        'type' => 'string',
        'notnull' => true,
        'length' => 255,
      ),
      'created_at' => array(
        'notnull' => true,
        'type' => 'timestamp',
        'length' => 25,
      )
    ),
    array(
      'type' => 'InnoDB',
      'primary' => array('id'),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));

    $this->createForeignKey('lot_log', 'lot_log_lot_id_lot_id', array(
      'name' => 'lot_log_lot_id_lot_id',
      'local' => 'lot_id',
      'foreign' => 'id',
      'foreignTable' => 'lot',
      'onDelete' => 'cascade',
    ));

    $this->addIndex('lot_log', 'lot_log_lot_id', array('fields' => array('lot_id')));
  }

  public function down()
  {
    $this->dropForeignKey('lot_log', 'lot_log_lot_id_lot_id');
    $this->removeIndex('lot_log', 'lot_log_lot_id', array('fields' => array('lot_id')));
    $this->dropTable('lot_log');
  }

}
