objectSuccess:
  components:
    one:          [menu, csstat]
brokerSuccess:
  components:
    one:          [menu, csstat]
querySuccess:
  components:
    one:          [menu, csstat]
recommendationSuccess:
  components:
    one:          [menu, csstat]recommendationSuccess